# Generated by Django 3.0 on 2021-08-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20210825_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='juego.Categoria')),
            ],
            bases=('juego.categoria',),
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='aciertos',
            new_name='acierto_1',
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='acierto_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juego.Modalidad'),
        ),
    ]
