# Generated by Django 3.0 on 2021-08-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_auto_20210828_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidad',
            name='categoria_ptr',
        ),
        migrations.AddField(
            model_name='modalidad',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
